version: "3"

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - .db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  application:
    depends_on:
      - "database"
    build: .
    ports:
      - "3000:3000"
    env_file:
      - docker.env
    volumes:
      - ".:/store_app"
    networks:
      - mynetwork
    tmpfs:
      - /store_app/tmp/pids/
networks:
  mynetwork:
    driver: bridge
