
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: <%= ENV["PASSWORD"] %>
  host: <%= ENV["HOST"] %>
  port: 5432
  database: bible_ia_development

test:
  <<: *default
  username: postgres
  password: <%= ENV["PASSWORD"] %>
  host: <%= ENV["HOST"] %>
  port: 5432
  database: bible_ia_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
