
default: &default
  adapter: postgresql
  encoding: unicode
  username: ENV["USERNAME"]
  password: ENV["PASSWORD"]
  host: ENV["HOST"]
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bible_ia_development

test:
  <<: *default
  database: bible_ia_test

production:
  <<: *default
  url: ENV["DATABASE_URL"]
